### ISSUE TITLE
Getting Empty Array In Detections Instead Of Object

### ISSUE THREAD

**Issue by shivarajnaidu** [rcaceiro/node-yolo#1]
```js

const yolo = require('@vapi/node-yolo');
const darknetConfigs = './';
const detector = new yolo(darknetConfigs, "./cfg/coco.data", "./cfg/yolo.cfg", "./yolov3.weights");
detector.detect('./data/dog.jpg')
    .then(detections => {
    	console.log(detections)
    })
    .catch(error => {
        // here you can handle the errors. Ex: Out of memory
        console.error(error);
    });

```

Not getting any detection values... just empty array..

![image](https://user-images.githubusercontent.com/12374494/44140543-fa0ba0c8-a097-11e8-8686-775503ce668c.png)

**Comment by rcaceiro** [comment]
ok, shivarajnaidu, we thanks you for your help to improve this module.
We will check this to understand what is going on.
We will be in touch

**Comment by shivarajnaidu** [comment]
Thanks for your quick response... By the way I forgot to tell .. That I am using Ubuntu (KDE) 18.04 for this testing.. If I can get quick fix for this .. it would be very helpful for me..

**Comment by freakstatic** [comment]
Hi shivarajnaidu,
is this the image that you are using?

![dog](https://user-images.githubusercontent.com/7486476/44298489-db903a00-a2db-11e8-9873-236bbbf45ee2.jpg)

**Comment by freakstatic** [comment]
Can you show us your "npm install" output?

**Comment by rcaceiro** [comment]
Hi shivarajnaidu,
Can you respond to the previous questions for can check what happen.

**Comment by shivarajnaidu** [comment]
Yes I think.. @rcaceiro

**Comment by shivarajnaidu** [comment]
Sorry @freakstatic  I didn't have the outputs now...  Because I have switched to use Python for yolo bindings and.. making it work with NodeJs

**Comment by rcaceiro** [comment]
We test with dog.jpg image that came with darknet examples and worked properly on CPU and GPU.
Can you download the latest version to check if happens again?

**Comment by shivarajnaidu** [comment]
getting this error while installing node-yolo.. (I'm using Ubuntu 18.04 LTS)
![image](https://user-images.githubusercontent.com/12374494/45597692-ad426f00-b9ed-11e8-880c-b37dd6314130.png)

**Comment by freakstatic** [comment]
You have opencv installed?

**Comment by shivarajnaidu** [comment]
Sorry.. I'll install and test once again.. Thank you @freakstatic

**Comment by rcaceiro** [comment]
@shivarajnaidu we found a problem with opencv support and temporary removed it. We have launched a new version, can you install it and test it again.
You must delete node-modules folder and when run the following command:
`npm install`
