### ISSUE TITLE
threshold seems to be required

### ISSUE THREAD

**Issue by dennington-bear** [rcaceiro/node-yolo#6]
Probably just an update needed to the readme, just updated to the latest version and threshold seems to be required. From the docs it seems only the path is required but on my package I also need to include a threshold or else it wont run. Ive only tested it on the `detector.detectImage` function

**Comment by rcaceiro** [comment]
Hi @dennington-bear, sorry for the delay. I will check that out and fix the code to threshold be not required.

Best Regards

**Comment by rcaceiro** [comment]
I saw and the detectImage method requires the threshold, but I removed it and threshold is no longer mandatory.
