### ISSUE TITLE
link err!

### ISSUE THREAD

**Issue by gucy1972** [rcaceiro/node-yolo#7]
Installing @vapi/node-yolo@*/usr/bin/ld: cannot find -lopencv_videoio

hi, buddy, what is the problem?? help!

**Comment by rcaceiro** [comment]
Hi @gucy1972 you must have the OpenCV installed to compile the node-yolo

**Comment by paul019** [comment]
I installed OpenCV and still get the same error. Can you give instructions on how to install OpenCV? I ran:
```
brew install opencv@2
sudo chown -R $(whoami):admin /usr/local
brew link --force opencv@2
```

**Comment by paul019** [comment]
Now I managed to install OPENCV. I tried again to install node-yolo, but got the following error this time:
`fatal error: no viable conversion from 'cv::Mat' to 'IplImage' (aka '_IplImage')`

I suspect, that it has something to do with the version of OPENCV used. What version do you recommend?

**Comment by freakstatic** [comment]
Hi @paul019 
Try with the 3.4.3 version
