### ISSUE TITLE
error yolo_init: No such file or directory

### ISSUE THREAD

**Issue by celevra** [rcaceiro/node-yolo#9]
Hi,

i get a "no such file or directory" found error

```
shinobi blub # node test.js
error yolo_init: No such file or directory
{ errorMessage: 'Cannot instantiate due an error.',
  errorCode: 1,
  errorPrefix: 'yolo\u0000yolo_napi\u0000[empty_any]\u0000error' }
```

```
const Yolo = require('@vapi/node-yolo');
const detector = new Yolo("darknet_configs", "cfg/coco.data", "cfg/yolov3.cfg", "yolov3.weights");
detector.detectImage('data.jpg')
        .then(detections =>
        {
         console.log(detections);
         // here you receive the detections
        })
        .catch(error =>
        {
         console.log(error);
         // here you can handle the errors. Ex: Out of memory
        });
```

```
shinobi blub # ls -alh
total 104K
drwxr-xr-x 4 root root 4.0K Sep 30 14:28 .
drwxr-xr-x 7 root root 4.0K Sep 30 14:07 ..
drwxr-xr-x 4 root root 4.0K Sep 30 14:17 darknet-configs
-rw-r--r-- 1 root root  79K Sep 30 14:25 data.jpg
drwxr-xr-x 3 root root 4.0K Sep 30 14:16 node_modules
-rw-r--r-- 1 root root  332 Sep 30 14:16 package-lock.json
-rw-r--r-- 1 root root  438 Sep 30 14:28 test.js
```

do i have to specify the file in an other way?

regards

celevra

**Comment by freakstatic** [comment]
Sorry for the late response
Can you post the contents of your `darknet-configs`?

**Comment by DonavanMartin** [comment]
<img width="168" alt="Capture d’écran, le 2019-11-28 à 20 21 31" src="https://user-images.githubusercontent.com/7544240/69837412-ada6de80-121c-11ea-8964-bb99a9c68cb5.png">

**Comment by freakstatic** [comment]
Try to change the folder `darknet-configs` to `darknet_configs`

**Comment by DonavanMartin** [comment]
Humm... same error...

**Comment by DonavanMartin** [comment]
Solve, thank you for that fast response.

**Comment by freakstatic** [comment]
No problem, happy to help! :)

**Comment by DonavanMartin** [comment]
This is another related issue... look like another path issue... 
<img width="594" alt="Capture d’écran, le 2019-11-28 à 20 46 00" src="https://user-images.githubusercontent.com/7544240/69838118-180d4e00-1220-11ea-98d1-9326e82f9201.png">

**Comment by freakstatic** [comment]
We really need to improve the error reporting...
Can you send me your project to check what is the error?

**Comment by rick91236rick** [comment]
Hi,
I have the same problem , but  I can't find where is wrong.

Can someone help me?

This is my darknet-configs and code.
```
const Yolo = require('@vapi/node-yolo');

const detector = new Yolo("darknet_configs", "cfg/coco.data", "cfg/yolov3.cfg", "yolov3.weights");
detector.detectImage('test.jpg')
        .then(detections => {
                // here you receive the detections
        })
        .catch(error => {
                console.log(error)
                // here you can handle the errors. Ex: Out of memory
        });
```
![註解 2020-03-02 235211](https://user-images.githubusercontent.com/19178802/75692895-2cf6f300-5ce1-11ea-9a3d-146c07ae913e.png)



regards

Rick
